"""початкова схема

Revision ID: b65287cc1e04
Revises: 
Create Date: 2026-08-26 21:15:55.924093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65287cc1e04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('non_school_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kind', sa.Enum('HOLIDAY', 'VACATION', 'REMOTE', 'OTHER', name='daykind', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('non_school_day', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_non_school_day_date'), ['date'], unique=True)

    op.create_table('school_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('TEACHER', 'ADMIN', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invite_code', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_invite_code'), ['invite_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_teacher_tg_user_id'), ['tg_user_id'], unique=True)

    op.create_table('class_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'teacher_id', name='uq_assignment')
    )
    op.create_table('meal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('eating_count', sa.Integer(), nullable=False),
    sa.Column('present_count', sa.Integer(), nullable=True),
    sa.Column('entered_by_teacher_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('TEACHER', 'ADMIN', 'IMPORT', name='entrysource', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entered_by_teacher_id'], ['teacher.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'date', name='uq_entry_class_date')
    )
    with op.batch_alter_table('meal_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_entry_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_entry_date'), ['date'], unique=False)

    op.create_table('meal_entry_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Integer(), nullable=True),
    sa.Column('new_value', sa.Integer(), nullable=False),
    sa.Column('changed_by_teacher_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_teacher_id'], ['teacher.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_id'], ['meal_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_entry_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_entry_audit_entry_id'), ['entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_entry_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_entry_audit_entry_id'))

    op.drop_table('meal_entry_audit')
    with op.batch_alter_table('meal_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_entry_date'))
        batch_op.drop_index(batch_op.f('ix_meal_entry_class_id'))

    op.drop_table('meal_entry')
    op.drop_table('class_assignment')
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_invite_code'))

    op.drop_table('teacher')
    op.drop_table('school_class')
    with op.batch_alter_table('non_school_day', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_non_school_day_date'))

    op.drop_table('non_school_day')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
