"""vidsutni ta khvori

Revision ID: e32a7fd85849
Revises: fe4ffdaaa16c
Create Date: 2026-09-03 13:00:14.463326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32a7fd85849'
down_revision: Union[str, Sequence[str], None] = 'fe4ffdaaa16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absent_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sick_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('meal_entry_audit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changed_field', sa.Enum('EATING', 'ABSENT', 'SICK', name='mealfield', native_enum=False), server_default='EATING', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_entry_audit', schema=None) as batch_op:
        batch_op.drop_column('changed_field')

    with op.batch_alter_table('meal_entry', schema=None) as batch_op:
        batch_op.drop_column('sick_count')
        batch_op.drop_column('absent_count')

    # ### end Alembic commands ###
