"""unique index on teacher phone

Revision ID: fe4ffdaaa16c
Revises: b65287cc1e04
Create Date: 2026-08-28 11:22:58.171001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4ffdaaa16c'
down_revision: Union[str, Sequence[str], None] = 'b65287cc1e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_phone'))

    # ### end Alembic commands ###
